# Generated by Django 4.2.5 on 2023-10-03 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_product_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=100)),
                ("date", models.DateField(auto_now_add=True)),
                ("star", models.IntegerField()),
                ("review", models.TextField()),
                ("image", models.ImageField(null=True, upload_to="media")),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("price", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("total", models.IntegerField()),
                ("slug", models.SlugField(max_length=500)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.product"
                    ),
                ),
            ],
        ),
    ]
